### ISSUE TITLE
startPosition Picker View Not Visible

### ISSUE THREAD

**Issue by Dylan-Wells** [Swartdogs/PowerScout#16]
While running the app during a test, a problem that was found is that the climbing picker view works but the starting position does not operate and they look exactly identical in the code.

**Comment by Pr1sM** [comment]
The picker views are now accessible by selecting the button, like so:
![powerscoutpickers](https://user-images.githubusercontent.com/2002470/35493767-6d8343ee-047b-11e8-9a19-54c52e902898.gif)

**Comment by Pr1sM** [comment]
Fixed in #17
