### ISSUE TITLE
Test functionality of App for 1.0.0 Release

### ISSUE THREAD

**Issue by Pr1sM** [Swartdogs/PowerScout#29]
The app is pretty close to a 1.0.0 release and needs to be tested thoroughly before creating a release tag. After this point, this project will follow [semantic versioning](https://semver.org) and future pull release merges should create a patch, minor, or major version bump depending on the changes made.

Once these features have been verified, a new tag can be created marking the 1.0.0 release.

Features to be tested:
- Data Entry
  - Team Info
    - [x] App will not continue unless required info is filled out (Team number, Match number, and alliance)
    - [x] Continuing with a match will cause data entry view to be shown
    - [x] Selecting No Show (in addition to required fields) will add a new no show match and no further data entry will be required for this match
  - Game Info
    - [x] All controls work as expected
    - [x] Cancellation of data entry can occur at any time and the data is not saved
    - [x] Clicking the 'done' button will complete the match (only if required information is entered)
  - Match Results
    - [x] Selecting completed matches will show all information in a detail view
    - [x] Match result data is the same as the information entered (both raw values and rendered text)
- Data Transfer
    - [x] Data transfer occurs between two iPads
    - [x] All data is sent correctly
    - [x] data that was previously transferred no longer automatically appears on the 'select' list
- Data Export
    - [x] Data can be exporting via iTunes file sharing

**Comment by McIntyre227** [comment]
All the Team Info seems to work as planned.

**Comment by McIntyre227** [comment]
For the Game Info - 1) It let's me advance to the Final Results screen without selecting a Starting Position or a Climbing Attempt. 2) The 'done' button says 'results', but it does bring up the Final Results Pop Up. 3) The biggest issue is with the two scroll select entry points. As you are selecting the scroll item, the scroll gets larger and can stay that way even if the user moves to another element to select (for example the yes/no of the Crossed Auto Line). I don't know if the app actually collects the selection in the scroll entry with it large, but other items on the screen disappear. Because of this, I did not check the box where all control work as selected.

**Comment by McIntyre227** [comment]
For the Final Info - This page appears to work as desired

**Comment by McIntyre227** [comment]
The Match Results Page - Selecting a completed match will bring up that match's data on the match info page. It shows the Team Info and the Final Results. Is it supposed to give the Data Entry Data? That information is not there. Also, under the Final Results portion, there is a spot for Yellow Cards and Red Cards. We have decided not to collect this data in the app this year. It appears that the data that is shown is indeed the data that was entered, just not all the data entered.

**Comment by McIntyre227** [comment]
I am not able to test the data transfer from iPad to iPad. For the data export, when I bring up iTunes and look at the apps available on the iPad, PowerUp Scouting is not on the list, therefore I am not able to download the CSV file. Lastly, we need to put an icon on the app. Right now it's the generic app icon.

**Comment by Pr1sM** [comment]
We will also need to merge the constraint changes from [DylansBranch](https://github.com/Swartdogs/PowerScout/tree/DylansBranch) to master. This can be done by making a pull request detailing the changes made into the master branch.

**Comment by Pr1sM** [comment]
The Match Results page is a combination of two pages, the Game specific results and the basic team and final info. You can access the game specific data by dragging down the "Match Info" tab or tapping the "Score Results" tab. Here is a demonstration (sorry the gif isn't the best quality!):
![resultsview](https://user-images.githubusercontent.com/2002470/36185555-5aa740c8-10ff-11e8-9dfd-2549278ed172.gif)

We can adjust this ordering to show the game specific results first instead of the match info if that is preferable.

**Comment by Pr1sM** [comment]
I've added #35, #36, #37 for the Data Entry changes, #34 for the app icon, and #38 for the removal of penalties in the results view.

**Comment by Pr1sM** [comment]
The file exporting was added in #32, you may have an earlier version of the app before this was added.

**Comment by McIntyre227** [comment]
The Match Results page is just fine how it is. I am just unobservant. Thank you for the animation. All of the data is on the score results page. The only difference I see is the terminology from the data entry page. NES is listed as Not at Exchange, Climbing Helping another Team is Climb and Assisted Another, No Attempt of Failure to Climb is None, No Climb but Helped another is Assisted Other, Climb by Themselves is Solo Climb, Climb with Help is Climb with Assistance. This is what I have on this for now. I will test this match results page further. There is a lot to check.

**Comment by Pr1sM** [comment]
Status Update: We are waiting on #41 and #55 to merge and #52 / #49 to be resolved before completing this.

**Comment by Pr1sM** [comment]
With #59 merged, I think we have completed all of the basic functionality required for a 1.0 Release, I'll make a tag so the state of the app will be marked. Nice job everyone!
