### ISSUE TITLE
Change continue button in Data Entry View

### ISSUE THREAD

**Issue by Pr1sM** [Swartdogs/PowerScout#36]
There is some ambiguity right now with the continue button in the Data Entry View. The "cancel" button on the left is clear in its function, but the "results" button on the right could mean a number of things:
- Continue to the Final Results Screen
- Show the match results

Because of this, the label of this button should be changed to "Done" so it is clearer.

**Comment by McIntyre227** [comment]
I vote for "Done"

**Comment by MattDaoud225** [comment]
Ok so now it says done and I'm working on it actually changing the page.

**Comment by Pr1sM** [comment]
You shouldn't have to change the function at all, this is a cosmetic change only. The new Done button should still launch the Final Results view as before.
