### ISSUE TITLE
Remove Penalty Data from Results View

### ISSUE THREAD

**Issue by Pr1sM** [Swartdogs/PowerScout#38]
The Penalty counters are not being used and should be removed from the results view.

The following changes need to be made
- Remove the label groups for the 4 penalty types in the Results Storyboard
- Remove the [label variables](https://github.com/Swartdogs/PowerScout/blob/master/PowerScout/DetailControllers/Results/ResultsMatchInfoViewController.swift#L19-L22) in the Match Info Results view
- Remove the associate usages in the Match Info Results View

**Comment by MattDaoud225** [comment]
Finished in Matthew's Branch

**Comment by Pr1sM** [comment]
For the sake of consistency and a way to easily tell which issues have not been resolved in the master branch, we only want to close issues when a PR has been merged. I'm reopening this until a PR is made and merged into the master branch.

**Comment by Pr1sM** [comment]
This was fixed in #43
