### ISSUE TITLE
UI Picker View Needs to have none switched to No attempt

### ISSUE THREAD

**Issue by MattDaoud225** [Swartdogs/PowerScout#48]
The none option in the climb ui picker must have none switched to No Attempt.

**Comment by MattDaoud225** [comment]
I looked through the code and couldn't find where to change that value in the climbing picker view. If someone can look through it and fix it that would be great.

**Comment by Pr1sM** [comment]
As of #39, There's only one location you need to change for this. 

The line you'll have to change is [here](https://github.com/Swartdogs/PowerScout/blob/master/PowerScout/Models/Definitions/PowerEndClimbPositionType.swift#L24)

This last portion of the line has the "None" string, which can be changed to "No Attempt"
