### ISSUE TITLE
Finalize PowerMatch Data Metrics

### ISSUE THREAD

**Issue by Pr1sM** [Swartdogs/PowerScout#5]
The `DataEntryViewController` controls are a work in progress, but the data that needs to be stored for each match must be packaged based on a known scheme so it can be exported properly. Most of the scaffolding has been created for a basic [match](https://github.com/Swartdogs/PowerScout/blob/master/PowerScout/Models/Match.swift), but specific metrics should be defined and integrated similarly to the [SteamMatch](https://github.com/Swartdogs/PowerScout/blob/master/PowerScout/Models/SteamMatch.swift) object.

**Comment by Pr1sM** [comment]
I haven't seen any discussion on this, but I'd like to keep this moving so we can start creating and saving matches (the most __important__ feature of the app). Based on the DataEntryViewController, these are metrics I think are needed:

|Name|Value|Already Included in `Match` Superclass|Description|
|:----:|:----:|:----:|:-----|
|teamNumber|`Int`|Yes|The number of the team being scouted|
|matchNumber|`Int`|Yes|The match being scouted|
|startingPosition|`Enum`|No|The starting position of the robot|
|autoCrossedLine|`Bool`|No|Whether or not the robot crossed the auto line during autonomous (performed an "auto-run")|
|autoScaleBlocks|`Int`|No|The number of blocks placed on the scale during autonomous|
|autoSwitchBlocks|`Int`|No|The number of blocks placed on the switch during autonomous|
|teleScaleBlocks|`Int`|No|The number of blocks placed on the scale during teleop|
|teleSwitchBlocks|`Int`|No|The number of blocks placed on the switch during teleop|
|teleExchangeBlocks|`Int`|No|The number of blocks delivered to the exchange|
|teleLow|`Bool`|No|??? - Need to fill this out|
|teleNormal|`Bool`|No|??? - Need to fill this out|
|teleHigh|`Bool`|No|??? - Need to fill this out|
|endClimb|`Bool`|No|Whether or not the robot performed a climb|
|endClimbCondition|`Enum`|No|What type of climb the robot performed|

Are these correct? If not, add a comment below detailing what needs to fixed/added. I will start working off of this table and address the changes in follow-up commits.

**Comment by McIntyre227** [comment]
We decided that we don't need the endClimb. We are just going to go with the endClimbCondition. The teleLow, teleNormal, teleHigh are the 3 positions of the Scale when a team places a block. Lastly, all the "Blocks" should be Cubes.
