### ISSUE TITLE
Remove Low (yes/no), Balanced (yes/no), High (yes/no)

### ISSUE THREAD

**Issue by McIntyre227** [Swartdogs/PowerScout#74]
### Issue Description

(a brief summary of your issue)

### You Environment
- App Version:
- iOS Version:
- Device Type: (ex. iPad 2, iPad Air, ...)
> You can also include the model number by looking at: Settings > General > About

### Steps to Reproduce
- Include a list of steps that will reproduce your issue
- Add a note if you can only reproduce the issue intermittently

### Expected Behavior

( A brief description of what you expect to happen)

### Actual Behavior

( A brief description of what is actually happening)

**Comment by McIntyre227** [comment]
At the 1st Regional, these selections were not used, so we decided we don't need them.

**Comment by Pr1sM** [comment]
@Dylan-Wells I've moved this back to In Progress until the change has reached the master branch. Make a PR into the master branch (see [this](https://help.github.com/articles/creating-a-pull-request/) for more details on how to do this). Once the PR gets merged, we can then close this issue and move it to the done column.
