### ISSUE TITLE
Yes/No for "cross" of field

### ISSUE THREAD

**Issue by Dylan-Wells** [Swartdogs/PowerScout#75]
We'd like to add a yes or no for crossing the field over to placing a cube on the switch or scale. (Example: Starting from Exchange side but placing a cube on NES scale)

**Comment by MattDaoud225** [comment]
I plan to talk to Dylan to get more information about this so that it can be implemented.

**Comment by MattDaoud225** [comment]
I understand what the item was and have implemented the UI elements.

**Comment by Pr1sM** [comment]
@MattDaoud225 You will have to modify the `PowerMatch` class to create a variable to store this value between app runs and when you export the match. See [this comment](https://github.com/Swartdogs/PowerScout/issues/80#issuecomment-373141151) for more details on how to do this.
