### ISSUE TITLE
Count of Cubes missed (Teleop and Auto)

### ISSUE THREAD

**Issue by Dylan-Wells** [Swartdogs/PowerScout#76]
We'd like to add the counter for missed cubes placed for both the switch and the scale in both autonomous and teleop. After we have both of these, we can start to account for placement accuracy in the data spreadsheet.

**Comment by MattDaoud225** [comment]
UI elements are implemented in data entry and results view needs to be wired to show on results page however and in export file.

**Comment by Pr1sM** [comment]
@MattDaoud225 You will have to modify the `PowerMatch` class using a similar set of steps as [this comment](https://github.com/Swartdogs/PowerScout/issues/80#issuecomment-373141151). the location of this will likely be in "auto" and "tele" section instead of "endg".
