### ISSUE TITLE
Yes/No for a robot playing defense

### ISSUE THREAD

**Issue by Dylan-Wells** [Swartdogs/PowerScout#77]
We'd like a yes or no for robots playing defense so that when we look at the spreadsheet it can help show which robots have played defense in qualifications.

**Comment by MattDaoud225** [comment]
I added the needed UI pieces to the results page

**Comment by Pr1sM** [comment]
@MattDaoud225 @Dylan-Wells 

You will have to change the `PowerMatch` class to store the data and correctly export it. See  [this comment](https://github.com/Swartdogs/PowerScout/issues/80#issuecomment-373141151) for a similar set of steps to do this. Doing this will also make it available to consume set and get the variable in the data entry and results page.
